<?php

/**
 * Smistamento: preferences, excluded folders, Sieve script generation, small localization helpers.
 *
 * @license GNU GPLv3+
 */
class smistamento_core
{
    public const DIGESTS = ['off', 'day', 'week', 'month'];
    public const SPAM_ACTIONS = ['trash', 'discard'];

    /** First line of the managed script; the JSON with the settings follows on the second line. */
    public const SCRIPT_MARK = '# Smistamento: generated by the Roundcube plugin «smistamento». Do not edit: every save rewrites it.';
    public const JSON_PREFIX = '# smistamento-settings: ';

    /** Folder names treated as Junk/Trash even without SPECIAL-USE (case-insensitive, last path segment). */
    public const JUNK_NAMES = ['junk', 'spam', 'posta indesiderata', 'junk e-mail', 'junk email', 'bulk mail'];
    public const TRASH_NAMES = ['trash', 'cestino', 'deleted', 'deleted items', 'deleted messages', 'bin'];

    /**
     * Normalized settings.
     *
     * @param array $raw      ['folders' => [imap name => [active, read, digest]], time, weekday, monthday]
     * @param array $defaults same shape (config defaults; folders keyed by path)
     */
    public static function normalize(array $raw, array $defaults = [])
    {
        $folders = [];
        foreach ((array) ($raw['folders'] ?? []) as $name => $f) {
            $folders[(string) $name] = self::folder_entry($f);
        }

        $time = (string) ($raw['time'] ?? $defaults['time'] ?? '07:30');
        if (!preg_match('/^([01]\d|2[0-3]):[0-5]\d$/', $time)) {
            $time = '07:30';
        }
        $weekday = (int) ($raw['weekday'] ?? $defaults['weekday'] ?? 1);
        $monthday = (int) ($raw['monthday'] ?? $defaults['monthday'] ?? 1);

        return [
            'folders' => $folders,
            'spam' => self::spam_entry($raw['spam'] ?? null, $defaults['spam'] ?? []),
            'time' => $time,
            'weekday' => $weekday >= 1 && $weekday <= 7 ? $weekday : 1,
            'monthday' => $monthday >= 1 && $monthday <= 28 ? $monthday : 1,
        ];
    }

    public static function folder_entry($f)
    {
        $f = (array) $f;
        return [
            'active' => !empty($f['active']),
            'read' => !empty($f['read']),
            'digest' => in_array($f['digest'] ?? 'off', self::DIGESTS, true) ? $f['digest'] : 'off',
        ];
    }

    /**
     * «Spam» row: active, threshold (soglia Spam), trash_threshold (soglia Cestino), action (trash|discard).
     * Thresholds are '0.10'..'0.95', two decimals, and threshold < trash_threshold:
     *   conf < threshold -> stays in the Inbox; threshold <= conf < trash_threshold -> Spam folder;
     *   conf >= trash_threshold -> action. No confidence -> Spam folder.
     * Old settings (one threshold, no trash_threshold): the old threshold becomes the Spam threshold and
     * the Cestino threshold is 0.80, or the old value if higher. When the old value is 0.80 or more the two
     * would be equal, so the Spam threshold goes 0.05 lower (the old «Sopra la soglia» point stays the same).
     */
    public static function spam_entry($s, array $defaults = [])
    {
        $ok = static function ($t) {
            return is_string($t) && preg_match('/^0\.\d\d$/', $t) && $t >= '0.10' && $t <= '0.95';
        };
        $num = static function ($v) {
            return $v === null ? null : str_replace(',', '.', trim((string) $v));
        };

        $dt = $num($defaults['threshold'] ?? null);
        $dc = $num($defaults['trash_threshold'] ?? null);
        $dt = $ok($dt) ? $dt : '0.40';
        $dc = $ok($dc) ? $dc : self::migrate_trash($dt);
        if ($dt >= $dc) {
            [$dt, $dc] = ['0.40', '0.80'];
        }
        $d = ['active' => !empty($defaults['active'] ?? true), 'action' => (string) ($defaults['action'] ?? 'trash')];

        $s = is_array($s) ? $s : [];
        $t = $num($s['threshold'] ?? null);
        $c = $num($s['trash_threshold'] ?? null);
        $t = $ok($t) ? $t : $dt;
        if (!$ok($c)) {
            // old single-threshold settings, or no settings yet
            $c = array_key_exists('threshold', $s) && !array_key_exists('trash_threshold', $s) ? self::migrate_trash($t) : $dc;
        }
        if ($t >= $c) {
            $t = sprintf('0.%02d', max(10, (int) round($c * 100) - 5));
            if ($t >= $c) {
                [$t, $c] = [$dt, $dc];
            }
        }
        $a = (string) ($s['action'] ?? $d['action']);
        return [
            'active' => array_key_exists('active', $s) ? !empty($s['active']) : $d['active'],
            'threshold' => $t,
            'trash_threshold' => $c,
            'action' => in_array($a, self::SPAM_ACTIONS, true) ? $a : 'trash',
        ];
    }

    /** Cestino threshold for an old single-threshold setting: 0.80, or the old value if higher. */
    private static function migrate_trash($old)
    {
        return $old > '0.80' ? $old : '0.80';
    }

    /**
     * Save check for the Spam row: '' when the two thresholds are valid, else the error label.
     * The values come straight from the form (comma or dot).
     */
    public static function spam_check($threshold, $trash_threshold)
    {
        $t = str_replace(',', '.', trim((string) $threshold));
        $c = str_replace(',', '.', trim((string) $trash_threshold));
        $valid = array_flip(self::spam_thresholds());
        if (!isset($valid[$t]) || !isset($valid[$c])) {
            return 'spam_err_value';
        }
        return $t < $c ? '' : 'spam_err_order';
    }

    /** Thresholds offered in the settings: 0.10, 0.15 … 0.95. */
    public static function spam_thresholds()
    {
        $out = [];
        for ($i = 10; $i <= 95; $i += 5) {
            $out[] = sprintf('0.%02d', $i);
        }
        return $out;
    }

    /** Active folder names. */
    public static function active_folders(array $p)
    {
        return array_keys(array_filter($p['folders'], static function ($f) { return $f['active']; }));
    }

    /**
     * Folders that can never be activated: Inbox, Drafts, Sent, Junk/Spam, Trash
     * (special-use + configured special folders + common names).
     *
     * @return array ['all' => [...], 'junk' => [...], 'trash' => [...]]
     */
    public static function excluded_folders(rcube_storage $storage)
    {
        $special = (array) $storage->get_special_folders();
        $junk = $trash = [];
        $all = ['INBOX'];

        foreach ($special as $type => $folder) {
            if (!$folder) {
                continue;
            }
            $all[] = $folder;
            if ($type == 'junk') {
                $junk[] = $folder;
            } elseif ($type == 'trash') {
                $trash[] = $folder;
            }
        }

        foreach ((array) $storage->list_folders('', '*', 'mail', null, true) as $folder) {
            $attrs = array_map('strtolower', (array) ($storage->folder_attributes($folder) ?: []));
            $leaf = mb_strtolower(self::leaf($storage, $folder));
            if (in_array('\\junk', $attrs) || in_array($leaf, self::JUNK_NAMES)) {
                $junk[] = $folder;
                $all[] = $folder;
            } elseif (in_array('\\trash', $attrs) || in_array($leaf, self::TRASH_NAMES)) {
                $trash[] = $folder;
                $all[] = $folder;
            } elseif (in_array('\\sent', $attrs) || in_array('\\drafts', $attrs)) {
                $all[] = $folder;
            }
        }

        return ['all' => array_values(array_unique($all)), 'junk' => array_values(array_unique($junk)),
            'trash' => array_values(array_unique($trash))];
    }

    /** Last path segment, UTF-8. */
    public static function leaf(rcube_storage $storage, $folder)
    {
        $parts = self::parts($storage, $folder);
        return end($parts);
    }

    /** IMAP name (UTF7-IMAP) -> UTF-8 segments. */
    public static function parts(rcube_storage $storage, $folder)
    {
        $delim = $storage->get_hierarchy_delimiter();
        $parts = $delim ? explode($delim, $folder) : [$folder];
        return array_map(static function ($p) { return rcube_charset::convert($p, 'UTF7-IMAP'); }, $parts);
    }

    /** Label path "Progetti/2026" (see smistamento_labels). */
    public static function path(rcube_storage $storage, $folder)
    {
        return $folder === 'INBOX' ? 'INBOX' : implode('/', self::parts($storage, $folder));
    }

    /** Display «Progetti / 2026». */
    public static function display_name(rcube_storage $storage, $folder)
    {
        if ($folder === 'INBOX') {
            return rcube::get_instance()->gettext('inbox');
        }
        return implode(' / ', self::parts($storage, $folder));
    }

    /** Mailbox name as Sieve fileinto / doveadm want it: UTF-8, server delimiter. */
    public static function utf8_name($folder)
    {
        return rcube_charset::convert($folder, 'UTF7-IMAP');
    }

    // -----------------------------------------------------------------------------------------
    // Managed Sieve script
    // -----------------------------------------------------------------------------------------

    /**
     * Build the managed script.
     *
     * @param array $p        normalized settings (folders keyed by IMAP name)
     * @param array $info     [imap name => ['mailbox' => utf8 name, 'labels' => [...], 'path' => ...]] for the folders in $p
     * @param array $opts     label_header, conf_header, min_conf, inbox_labels, spam, user, lang, timezone
     */
    public static function build_script(array $p, array $info, array $opts)
    {
        $q = static function ($s) {
            return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], (string) $s) . '"';
        };
        $ql = static function (array $list) use ($q) {
            return '[' . implode(', ', array_map($q, $list)) . ']';
        };

        // settings for server-side jobs (digest), one JSON line
        $json = ['v' => 2, 'user' => $opts['user'] ?? '', 'lang' => $opts['lang'] ?? 'it_IT', 'timezone' => $opts['timezone'] ?? null, 'time' => $p['time'], 'weekday' => $p['weekday'],
            'monthday' => $p['monthday'], 'label_header' => $opts['label_header'], 'conf_header' => $opts['conf_header'], 'min_conf' => $opts['min_conf'],
            'inbox_labels' => array_values($opts['inbox_labels'] ?? []), 'spam' => null, 'folders' => []];
        $spam = $opts['spam'] ?? null; // ['mailbox', 'path', 'trash', 'labels'] of the special Junk/Trash folders, or null
        if ($spam && !empty($spam['labels'])) {
            $json['spam'] = ['mailbox' => $spam['mailbox'], 'path' => $spam['path'], 'trash' => $spam['trash'],
                'labels' => array_values($spam['labels'])] + $p['spam'];
        }
        foreach ($p['folders'] as $name => $f) {
            if (!isset($info[$name])) {
                continue;
            }
            $json['folders'][] = ['mailbox' => $info[$name]['mailbox'], 'path' => $info[$name]['path'],
                'labels' => array_values($info[$name]['labels']),
                'active' => $f['active'], 'read' => $f['read'], 'digest' => $f['digest']];
        }

        $h = $opts['label_header'];
        $c = $opts['conf_header'];
        $min = $opts['min_conf'];

        $s = self::SCRIPT_MARK . "\n"
            . self::JSON_PREFIX . json_encode($json, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n"
            . "# Runs after the user's own filters: Dovecot only gets here if they did not file the mail.\n"
            . "require [\"fileinto\", \"imap4flags\", \"relational\", \"comparator-i;ascii-numeric\"];\n\n"
            . "# Spam and malware are never sorted by Smistamento.\n"
            . "if anyof (header :is \"X-Spam-Flag\" \"YES\", header :is \"X-Malware-Bazaar\" \"hit\") {\n  stop;\n}\n";

        if (!empty($opts['inbox_labels'])) {
            $s .= "\n# Mail from people stays in the Inbox, whatever the confidence.\n"
                . 'if header :is ' . $q($opts['label_header']) . ' ' . $ql(array_values($opts['inbox_labels'])) . " {\n  stop;\n}\n";
        }

        if ($json['spam'] && $json['spam']['active']) {
            $sp = $json['spam'];
            $act = $sp['action'] == 'discard' ? 'discard;' : 'fileinto ' . $q($sp['trash']) . ';';
            $cq = $q($opts['conf_header']);
            $s .= "\n# Spam (Laya). The general threshold does not apply. No confidence: Spam folder.\n"
                . "# Below " . $sp['threshold'] . ": stays in the Inbox. From " . $sp['threshold'] . " to below " . $sp['trash_threshold']
                . ": Spam folder. From " . $sp['trash_threshold'] . " up: " . ($sp['action'] == 'discard' ? 'deleted right away' : 'Trash') . ".\n"
                . 'if header :is ' . $q($opts['label_header']) . ' ' . $ql($sp['labels']) . " {\n"
                . '  if anyof (not exists ' . $cq . ', header :is ' . $cq . " \"\") {\n"
                . '    fileinto ' . $q($sp['mailbox']) . ";\n    stop;\n  }\n"
                . '  if header :value "ge" :comparator "i;octet" ' . $cq . ' ' . $q($sp['trash_threshold']) . " {\n"
                . '    ' . $act . "\n    stop;\n  }\n"
                . '  if header :value "ge" :comparator "i;octet" ' . $cq . ' ' . $q($sp['threshold']) . " {\n"
                . '    fileinto ' . $q($sp['mailbox']) . ";\n    stop;\n  }\n"
                . "  stop;\n}\n";
        }

        if ($min !== null && $min !== '') {
            $s .= "\n# No confidence, or below " . $min . ": stays in the Inbox.\n"
                . 'if anyof (not exists ' . $q($c) . ', header :value "lt" :comparator "i;octet" ' . $q($c) . ' ' . $q($min) . ") {\n  stop;\n}\n";
        }

        $rules = 0;
        foreach ($p['folders'] as $name => $f) {
            if (!$f['active'] || empty($info[$name]['labels'])) {
                continue;
            }
            $s .= "\n# " . str_replace("\n", ' ', $info[$name]['path']) . "\n"
                . 'if header :is ' . $q($h) . ' ' . $ql($info[$name]['labels']) . " {\n"
                . '  fileinto ' . ($f['read'] ? ':flags "\\\\Seen" ' : '') . $q($info[$name]['mailbox']) . ";\n  stop;\n}\n";
            $rules++;
        }

        if (!$rules) {
            $s .= "\n# No active folder: every mail stays in the Inbox.\n";
        }

        return $s;
    }

    /** Settings JSON from a managed script, or null. */
    public static function parse_script($script)
    {
        foreach (preg_split('/\r?\n/', (string) $script, 5) as $line) {
            if (strpos($line, self::JSON_PREFIX) === 0) {
                $data = json_decode(substr($line, strlen(self::JSON_PREFIX)), true);
                return is_array($data) ? $data : null;
            }
        }
        return null;
    }

    // -----------------------------------------------------------------------------------------
    // Localization helpers
    // -----------------------------------------------------------------------------------------

    /** «sabato 3 ottobre» from [N, j, n, Y] and the plugin's labels. */
    public static function long_day(rcube_plugin $plugin, array $d)
    {
        $months = explode(',', $plugin->gettext('months'));
        $days = explode(',', $plugin->gettext('weekdays'));
        return strtr($plugin->gettext('fmt_updated'), [
            '{l}' => $days[((int) $d[0] + 6) % 7] ?? '',
            '{j}' => $d[1] ?? '',
            '{F}' => $months[(int) ($d[2] ?? 1) - 1] ?? '',
            '{Y}' => $d[3] ?? '',
        ]);
    }
}
